### PR TITLE
[translation] Add Catalan translation. Resolves #421

### LINKED ISSUE #421: [translation] catalan translation
Please check the translation files you want to add/fix/update:

 - [x] CLI banner: (apps/jreleaser/src/main/resources/org/jreleaser/cli/Banner*.properties)
 - [x] CLI bundle: (apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages*.properties)
 - [x] core bundle: (core/jreleaser-utils/src/main/resources/org/jreleaser/bundle/Messages*.properties)

A list of language codes can be found at https://sda.berkeley.edu/man41h/localelist.htm

### PR DESCRIPTION
**Pull request by anyulled**
Fixes #421 

### Context
Catalan translation

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

**Comment by anyulled** [comment]
Hi @aalmiray, I rebased my repo before making a pull request and had some issues resolving it. I was about to ask you to do a squash merge because of it. I also missed another file I'm going to add in another pull request.

I also saw that there's no Spanish translation. Could I do it?

**Comment by aalmiray** [comment]
Hi @anyulled, figured there was an issue by looking at the last set of commits. All is good now 😄 
Of course you can also submit a patch for Spanish 🎉

**Comment by anyulled** [comment]
thanks! I'll do it in the other pull request I opened

**Comment by anyulled** [comment]
No prob

**Pull request merged**
