### PR TITLE
fix: `projectNameCapitalized` now handles hyphens as spaces

### LINKED ISSUE #923: [core] Template name `projectNameCapitalized` does not replace hyphens by spaces
The [`projectNameCapitalized` template name](https://jreleaser.org/guide/latest/configuration/name-templates.html#_project) states that the project name is capitalized and hyphens are replaced by spaces, however, I am seeing a different output:

I have a project with the `<artifactId>` set to `quarkiverse-parent` and it outputs `QuarkiverseParent` (without any spaces).

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone https://github.com/quarkiverse/quarkiverse-parent.git`
2. Checkout the `jreleaser` branch: `git checkout jreleaser`
3. `export JRELEASER_ZULIP_API_KEY=foo` (it doesn't matter which value you use, the property is used in the topic subject and it's written in the build logs when the next step is executed)
4. Run `mvn jreleaser:announce`

You should see an output similar to:
```bash
[INFO]
[INFO] -----------------< io.quarkiverse:quarkiverse-parent >------------------
[INFO] Building Quarkiverse: Parent POM 11-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- jreleaser-maven-plugin:1.2.0:announce (default-cli) @ quarkiverse-parent ---
[INFO] JReleaser 1.2.0
[INFO]   - basedir set to /Users/ggastald/workspace/quarkiverse/quarkiverse-parent
[INFO] Loading variables from /Users/ggastald/.jreleaser/config.properties
[WARNING] Variables source /Users/ggastald/.jreleaser/config.properties does not exist
[INFO] Validating configuration
[INFO] Project version set to 11-SNAPSHOT
[INFO] Release is snapshot
[INFO] Timestamp is 2022-08-29T14:44:24.789182-03:00
[INFO] HEAD is at 58bc361
[INFO] Platform is osx-aarch_64
[INFO] dry-run set to false
[INFO] Generating changelog: target/jreleaser/release/CHANGELOG.md
[INFO] Announcing release
[INFO]   [zulip] channel: announce
[INFO]   [zulip] subject: QuarkiverseParent release
```

### Expected Behaviour

The `projectNameCapitalized` should output `Quarkiverse Parent` 

### Actual Behaviour

It outputs `QuarkiverseParent` 

### Environment Information

- **Operating System**: macOS 12.5.1
- **JReleaser Version:** 1.2.0
- **JDK Version:** 17

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #923

### Context
It fixes the `projectNameCapitalized` behavior

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

**Comment by gastaldi** [comment]
Something tells me that `getClassNameForLowerCaseHyphenSeparatedName` isn't the method that `projectNameCapitalized` should be calling 🤔

**Comment by aalmiray** [comment]
I thought `org.jreleaser.util.StringUtils.getNaturalName` would do the trick.

**Comment by gastaldi** [comment]
I thought so too, but `getNaturalName` doesn't work with hyphens

**Comment by aalmiray** [comment]
Got it. Good catch.

**Comment by aalmiray** [comment]
Thanks!

**Pull request merged**
