### PR TITLE
Feature: add google chat bot integration

### LINKED ISSUE #241: Add Google chatbot integration
**Is your feature request related to a problem? Please describe.**
I'd like to be able to announce releases using the google chat integration
**Describe the solution you'd like**
A new plugin for this integration

**Describe alternatives you've considered**
There were no other alternatives so far

**Additional context**
image

### PR DESCRIPTION
**Pull request by anyulled**
Adds google chatbot integration

image

Fixes #241 

### Context
This pull request enables integration with the google chatbot via incoming webhooks

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.md).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

**Comment by anyulled** [comment]
Update documentation is pending.
I suggest applying a squash when merging

**Comment by aalmiray** [comment]
@anyulled looks like the license headers in the new files missed an update, i.e, `./gradlew licenseFormat`.

**Comment by anyulled** [comment]
@aalmiray  Thanks!

**Comment by aalmiray** [comment]
@anyulled do you want me to take care of the docs?

**Comment by anyulled** [comment]
@aalmiray sure, no problem

**Pull request merged**
